## based on example application.yml -> https://github.com/spring-projects/spring-boot/blob/master/docs/application.yml

spring:
  application.name: weibo_application

  datasource:
    driverClassName: org.sqlite.JDBC
    url: jdbc:sqlite:weibo.db
    username: 
    password: 

  jpa:
     show-sql: true
     ## dialect: com.zhangqun.apps.weibo.SQLiteDialect
     database-platform: com.zhangqun.apps.weibo.SQLiteDialect
     hibernate:
       ddl-auto: create
       